"""Database creation

Revision ID: 8cab7fedf37d
Revises: 
Create Date: 2024-12-04 13:00:20.330306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.orm import sessionmaker

from config import Settings
from models import Role, User

revision = '8cab7fedf37d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('last_loging', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        Role.__table__, [
            {
                "id": 1,
                "name": "user"
            }
        ]
    )
    op.bulk_insert(
        Role.__table__, [
            {
                "id": 2,
                "name": "admin"
            }
        ]
    )

    op.bulk_insert(
        User.__table__, [
            {
                "login": Settings.login,
                "password": Settings.password,
                "email": Settings.email,
                "role": Settings.role
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Session = sessionmaker(bind=op.get_bind())
    session = Session()

    roles = session.query(Role).all()
    if roles:
        for role in roles:
            session.delete(role)
        session.commit()

    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
    roles = session.query(Role).all()
    if roles:
        for role in roles:
            session.delete(role)
        session.commit()

    user = session.query(User).filter_by(user_id=1).first()
    if user:
        session.delete(user)
        session.commit()
